<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'proj4php\\' => array($vendorDir . '/proj4php/proj4php/src'),
    'Slim\\Middleware\\' => array($vendorDir . '/tuupola/slim-basic-auth/src', $vendorDir . '/tuupola/slim-jwt-auth/src'),
    'Firebase\\JWT\\' => array($vendorDir . '/firebase/php-jwt/src'),
    'CorsSlim\\' => array($vendorDir . '/palanik/corsslim'),
    'Arcanedev\\QrCode\\' => array($vendorDir . '/arcanedev/qr-code/src'),
);
